
package com.titanic.ventapasajes.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WSServiciosHR", targetNamespace = "http://wshr.mtc.gob.pe/", wsdlLocation = "http://pruebawshr.mtc.gob.pe/WSServiciosHR.asmx?WSDL")
public class WSServiciosHR
    extends Service
{

    private final static URL WSSERVICIOSHR_WSDL_LOCATION;
    private final static WebServiceException WSSERVICIOSHR_EXCEPTION;
    private final static QName WSSERVICIOSHR_QNAME = new QName("http://wshr.mtc.gob.pe/", "WSServiciosHR");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://pruebawshr.mtc.gob.pe/WSServiciosHR.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WSSERVICIOSHR_WSDL_LOCATION = url;
        WSSERVICIOSHR_EXCEPTION = e;
    }

    public WSServiciosHR() {
        super(__getWsdlLocation(), WSSERVICIOSHR_QNAME);
    }

    public WSServiciosHR(WebServiceFeature... features) {
        super(__getWsdlLocation(), WSSERVICIOSHR_QNAME, features);
    }

    public WSServiciosHR(URL wsdlLocation) {
        super(wsdlLocation, WSSERVICIOSHR_QNAME);
    }

    public WSServiciosHR(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WSSERVICIOSHR_QNAME, features);
    }

    public WSServiciosHR(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSServiciosHR(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WSServiciosHRSoap
     */
    @WebEndpoint(name = "WSServiciosHRSoap")
    public WSServiciosHRSoap getWSServiciosHRSoap() {
        return super.getPort(new QName("http://wshr.mtc.gob.pe/", "WSServiciosHRSoap"), WSServiciosHRSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSServiciosHRSoap
     */
    @WebEndpoint(name = "WSServiciosHRSoap")
    public WSServiciosHRSoap getWSServiciosHRSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://wshr.mtc.gob.pe/", "WSServiciosHRSoap"), WSServiciosHRSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WSSERVICIOSHR_EXCEPTION!= null) {
            throw WSSERVICIOSHR_EXCEPTION;
        }
        return WSSERVICIOSHR_WSDL_LOCATION;
    }

}
